#spring.application.name=springBoot
#server.port=8080
#welcome.message = welcome to this world !!
#spring.oracle.console.enabled=true
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xepdb1
#spring.datasource.username=yendreddy
#spring.datasource.password=Durga1710
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=update
#management.endpoints.web.exposure.include="*"